### ISSUE TITLE
key as environment variable

### ISSUE THREAD

**Issue by jeremypumphrey** [OpenWhere/ecs-deploy#2]
Is it possible to pass they key and secret key in as environment variables? This would allow you to pass in the secrets to the docker run command without checking in the values or having them built in the image for all to see or use.

**Comment by owaaa** [comment]
It sure is possible and that's how we use it actually. You can do -e AWS_SECRET_ACCESS_KEY etc with the same values you normally would from the command line. Boto inside docker will pick it up. You can also mount your .aws directory with -v and even pass -e AWS_PROFILE. I will update the docs

**Comment by owaaa** [comment]
I've updated the ReadMe.md with some details to clarify so I'm going to close the issue but let me know if you have any other questions. Thanks

**Comment by jeremypumphrey** [comment]
Thanks
